version: "3.9"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: ariline
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - app-network
    restart: always

  redis:
    image: redis
    environment:
      REDIS_DB: 0
    ports:
      - "6379:6379"
    networks:
      - app-network
    restart: always

volumes:
  dbdata:

networks:
  app-network:
