database:
  host: localhost
  user: postgres
  password: 1234
  dbname: ariline
  port: 5432
  sslmode: disable
  timezone: Asia/Shanghai
redis:
  addr: localhost:6379
  db: 0
service:
  address: 8080

